language:
   python
  
  python:
  - "3.6"

  install:
  - pip install -r requirements.txt
  - pip install pytest-cov

  env: 
  - APP_SETTINGS='development'
  
  script:
  - py.test  --cov-report term --cov=app/test/v1

  after_success:
  - codecov